export const homeCardContent = [
  { name: "QC Approval", value: "12546" },
  { name: "New Users", value: "24" },
  { name: "Labels", value: "56" },
  { name: "Withdrawal Request", value: "34" },
  { name: "Service Request", value: "12" },
  { name: "In Issue", value: "32" },
];
export const DistributionOverviewContent = [
  { name: "QC Approval", value: "512" },
  { name: "In Review", value: "24" },
  { name: "Barcode", value: "34" },
  { name: "To Live", value: "10K" },
  { name: "In Issue", value: "24" },
];
export const releaseItems = [
  {
    name: "Buker Bhitor DJ Baje",
    type: "Error",
    img: "release.png",
    date: "Sep21, 2024",
    artist: "Arpita Modak",
  },
  {
    name: "Buker Bhitor DJ Baje",
    type: "Released",
    img: "release.png",
    date: "Sep21, 2024",
    artist: "Arpita Modak",
  },
  {
    name: "Buker Bhitor DJ Baje",
    type: "Released",
    img: "release-placeholder.png",
    date: "Sep21, 2024",
    artist: "Arpita Modak",
  },
  {
    name: "Buker Bhitor DJ Baje",
    type: "Takedown",
    img: "release.png",
    date: "Sep21, 2024",
    artist: "Arpita Modak",
  },
  {
    name: "Buker Bhitor DJ Baje",
    type: "Released",
    img: "release.png",
    date: "Sep21, 2024",
    artist: "Arpita Modak",
  },
  {
    name: "Buker Bhitor DJ Baje",
    type: "Takedown",
    img: "release.png",
    date: "Sep21, 2024",
    artist: "Arpita Modak",
  },

  {
    name: "Buker Bhitor DJ Baje",
    type: "Released",
    img: "release-placeholder.png",
    date: "Sep21, 2024",
    artist: "Arpita Modak",
  },
  {
    name: "Buker Bhitor DJ Baje",
    type: "Takedown",
    img: "release.png",
    date: "Sep21, 2024",
    artist: "Arpita Modak",
  },
  {
    name: "Buker Bhitor DJ Baje",
    type: "Released",
    img: "release.png",
    date: "Sep21, 2024",
    artist: "Arpita Modak",
  },
  {
    name: "Buker Bhitor DJ Baje",
    type: "Released",
    img: "release-placeholder.png",
    date: "Sep21, 2024",
    artist: "Arpita Modak",
  },
];
export const artistTable = [
  {
    artistName: "Arpita Modak",
    img: "Avatar.png",
    userName: "SBO Music",
    email: "sbomusic@gmail.com",
    date: "22 Jan 2025",
    count: "24",
    action: "",
  },
  {
    artistName: "Arpita Modak",
    img: "Avatar.png",
    userName: "SBO Music",
    email: "sbomusic@gmail.com",
    date: "22 Jan 2025",
    count: "24",
    action: "",
  },
  {
    artistName: "Arpita Modak",
    img: "Avatar.png",
    userName: "SBO Music",
    email: "sbomusic@gmail.com",
    date: "22 Jan 2025",
    count: "24",
    action: "",
  },
  {
    artistName: "Arpita Modak",
    img: "Avatar.png",
    userName: "SBO Music",
    email: "sbomusic@gmail.com",
    date: "22 Jan 2025",
    count: "24",
    action: "",
  },
  {
    artistName: "Arpita Modak",
    img: "Avatar.png",
    userName: "SBO Music",
    email: "sbomusic@gmail.com",
    date: "22 Jan 2025",
    count: "24",
    action: "",
  },
  {
    artistName: "Arpita Modak",
    img: "Avatar.png",
    userName: "SBO Music",
    email: "sbomusic@gmail.com",
    date: "22 Jan 2025",
    count: "24",
    action: "",
  },
];
export const labelsTable = [
  {
    name: "T Series",
    img: "Avatar.png",
    userName: "SBO Music",
    email: "sbomusic@gmail.com",
    date: "22 Jan 2025",
    count: "24",
    status: "PENDING",
    action: "",
  },
  {
    name: "Zee Music Co.",
    img: "Avatar.png",
    userName: "SBO Music",
    email: "sbomusic@gmail.com",
    date: "22 Jan 2025",
    count: "24",
    status: "PENDING",
    action: "",
  },
  {
    name: "Saregama",
    img: "Avatar.png",
    userName: "SBO Music",
    email: "sbomusic@gmail.com",
    date: "22 Jan 2025",
    count: "24",
    status: "PENDING",
    action: "",
  },
  {
    name: "Vevo",
    img: "Avatar.png",
    userName: "SBO Music",
    email: "sbomusic@gmail.com",
    date: "22 Jan 2025",
    count: "24",
    status: "REJECTED",
    action: "",
  },
  {
    name: "Saregama",
    img: "Avatar.png",
    userName: "SBO Music",
    email: "sbomusic@gmail.com",
    date: "22 Jan 2025",
    count: "24",
    status: "APPROVED",
    action: "",
  },
  {
    name: "Steam Music",
    img: "Avatar.png",
    userName: "SBO Music",
    email: "sbomusic@gmail.com",
    date: "22 Jan 2025",
    count: "24",
    status: "REJECTED",
    action: "",
  },
  {
    name: "Steam Music India",
    img: "Avatar.png",
    userName: "SBO Music",
    email: "sbomusic@gmail.com",
    date: "22 Jan 2025",
    count: "24",
    status: "APPROVED",
    action: "",
  },
  {
    name: "Zee Music Bangla",
    img: "Avatar.png",
    userName: "SBO Music",
    email: "sbomusic@gmail.com",
    date: "22 Jan 2025",
    count: "24",
    status: "APPROVED",
    action: "",
  },
  {
    name: "Vevo",
    img: "Avatar.png",
    userName: "SBO Music",
    email: "sbomusic@gmail.com",
    date: "22 Jan 2025",
    count: "24",
    status: "PENDING",
    action: "",
  },
];
export const QCApprovalTable = [
  {
    img: "release.png",
    email: "raj09@gmail.com",
    releaseName: "Ami Dur Hote Tomarei Dekhechi",
    artist: "Arpita Modak",
    userName: "SBO Music",
    label: "Moxa Beats",
    upc: "-",
    date: "22 Jan 2025, 12:45 PM",
    page: "QC Approval",
    type: "ERROR",
    action: "",
  },
  {
    img: "release.png",
    email: "raj09@gmail.com",
    releaseName: "Buker Bhitor DJ Baje",
    userName: "SBO Music",
    label: "Moxa Beats",
    upc: "-",
    date: "22 Jan 2025, 12:45 PM",
    artist: "Arpita Modak",
    page: "QC Approval",
    type: "Re-Submitted",
    action: "",
  },
  {
    img: "release.png",
    email: "raj09@gmail.com",
    releaseName: "Buker Bhitor DJ Baje",
    artist: "Arpita Modak",
    userName: "SBO Music",
    label: "Moxa Beats",
    upc: "5056828948531",
    date: "22 Jan 2025, 12:45 PM",
    page: "QC Approved",
    approvedBy: "Subhamay Karjee",
    type: "IN REVIEW",
    action: "",
  },
  {
    img: "release.png",
    email: "raj09@gmail.com",
    releaseName: "Buker Bhitor DJ Baje",
    artist: "Arpita Modak",
    userName: "SBO Music",
    label: "Moxa Beats",
    upc: "5056828948531",
    date: "22 Jan 2025, 12:45 PM",
    page: "QC Approval",
    type: "Re-Submitted",
    action: "",
  },
  {
    img: "release.png",
    email: "raj09@gmail.com",
    releaseName: "Buker Bhitor DJ Baje",
    artist: "Arpita Modak",
    userName: "SBO Music",
    label: "Moxa Beats",
    upc: "-",
    date: "22 Jan 2025, 12:45 PM",
    page: "QC Approval",
    type: "IN REVIEW",
    action: "",
  },
  {
    img: "release.png",
    email: "raj09@gmail.com",
    releaseName: "Buker Bhitor DJ Baje",
    artist: "Arpita Modak",
    userName: "SBO Music",
    label: "Moxa Beats",
    upc: "-",
    date: "22 Jan 2025, 12:45 PM",
    page: "QC Approval",
    type: "ERROR",
    action: "",
  },
  {
    img: "release.png",
    email: "raj09@gmail.com",
    releaseName: "Buker Bhitor DJ Baje",
    artist: "Arpita Modak",
    userName: "SBO Music",
    label: "Moxa Beats",
    upc: "-",
    date: "22 Jan 2025, 12:45 PM",
    page: "QC Approval",
    type: "ERROR",
    action: "",
  },
  {
    img: "release.png",
    email: "raj09@gmail.com",
    releaseName: "Buker Bhitor DJ Baje",
    artist: "Arpita Modak",
    userName: "SBO Music",
    label: "Moxa Beats",
    upc: "5056828948531",
    date: "22 Jan 2025, 12:45 PM",
    action: "",
    page: "QC Approval",
    type: "ERROR",
  },
  {
    img: "release.png",
    email: "raj09@gmail.com",
    releaseName: "Buker Bhitor DJ Baje",
    artist: "Arpita Modak",
    userName: "SBO Music",
    label: "Moxa Beats",
    upc: "-",
    date: "22 Jan 2025, 12:45 PM",
    action: "",
    page: "QC Approval",
    type: "ERROR",
  },
];
export const DistributionLiveTable = [
  {
    img: "release.png",
    email: "raj09@gmail.com",
    releaseName: "Buker Bhitor DJ Baje",
    userName: "SBO Music",
    label: "Moxa Beats",
    upc: "5056828948531",
    date: "22 Jan 2025, 12:45 PM",
    action: "",
    artist: "Arpita Modak",
    page: "QC Approval",
    type: "ERROR",
  },
  {
    img: "release.png",
    email: "raj09@gmail.com",
    releaseName: "Buker Bhitor DJ Baje",
    userName: "SBO Music",
    label: "Moxa Beats",
    upc: "5056828948531",
    date: "22 Jan 2025, 12:45 PM",
    action: "",
    artist: "Arpita Modak",
    page: "QC Approved",
    approvedBy: "Subhamay Karjee",
    type: "IN REVIEW",
  },
  {
    img: "release.png",
    email: "raj09@gmail.com",
    releaseName: "Buker Bhitor DJ Baje",
    userName: "SBO Music",
    label: "Moxa Beats",
    upc: "5056828948531",
    date: "22 Jan 2025, 12:45 PM",
    action: "",
    artist: "Arpita Modak",
    page: "QC Approval",
    type: "Re-Submitted",
  },
  {
    img: "release.png",
    email: "raj09@gmail.com",
    releaseName: "Buker Bhitor DJ Baje",
    userName: "SBO Music",
    label: "Moxa Beats",
    upc: "5056828948531",
    date: "22 Jan 2025, 12:45 PM",
    action: "",
    artist: "Arpita Modak",
    page: "QC Approval",
    type: "Re-Submitted",
  },
  {
    img: "release.png",
    email: "raj09@gmail.com",
    releaseName: "Buker Bhitor DJ Baje",
    userName: "SBO Music",
    label: "Moxa Beats",
    upc: "5056828948531",
    date: "22 Jan 2025, 12:45 PM",
    action: "",
    artist: "Arpita Modak",
    page: "QC Approval",
    type: "Re-Submitted",
  },
  {
    img: "release.png",
    email: "raj09@gmail.com",
    releaseName: "Buker Bhitor DJ Baje",
    userName: "SBO Music",
    label: "Moxa Beats",
    upc: "5056828948531",
    date: "22 Jan 2025, 12:45 PM",
    action: "",
    artist: "Arpita Modak",
    page: "QC Approval",
    type: "Re-Submitted",
  },
  {
    img: "release.png",
    email: "raj09@gmail.com",
    releaseName: "Buker Bhitor DJ Baje",
    userName: "SBO Music",
    label: "Moxa Beats",
    upc: "5056828948531",
    date: "22 Jan 2025, 12:45 PM",
    action: "",
    artist: "Arpita Modak",
    page: "QC Approval",
    type: "Re-Submitted",
  },
  {
    img: "release.png",
    email: "raj09@gmail.com",
    releaseName: "Buker Bhitor DJ Baje",
    userName: "SBO Music",
    label: "Moxa Beats",
    upc: "5056828948531",
    date: "22 Jan 2025, 12:45 PM",
    action: "",
    artist: "Arpita Modak",
    page: "QC Approval",
    type: "Re-Submitted",
  },
  {
    img: "release.png",
    email: "raj09@gmail.com",
    releaseName: "Buker Bhitor DJ Baje",
    userName: "SBO Music",
    label: "Moxa Beats",
    upc: "5056828948531",
    date: "22 Jan 2025, 12:45 PM",
    action: "",
    artist: "Arpita Modak",
    page: "QC Approval",
    type: "ERROR",
  },
];
export const DistributionIssueTable = [
  {
    img: "release.png",
    email: "raj09@gmail.com",
    releaseName: "Buker Bhitor DJ Baje",
    userName: "SBO Music",
    label: "Moxa Beats",
    upc: "5056828948531",
    issue: "Blocked",
    date: "22 Jan 2025, 12:45 PM",
    action: "",
    artist: "Arpita Modak",
    page: "QC Approval",
    type: "Re-Submitted",
  },
  {
    img: "release.png",
    email: "raj09@gmail.com",
    releaseName: "Buker Bhitor DJ Baje",
    userName: "SBO Music",
    label: "Moxa Beats",
    upc: "5056828948531",
    issue: "Takedown",
    date: "22 Jan 2025, 12:45 PM",
    action: "",
    page: "QC Approved",
    approvedBy: "Subhamay Karjee",
    type: "IN REVIEW",
  },
  {
    img: "release.png",
    email: "raj09@gmail.com",
    releaseName: "Buker Bhitor DJ Baje",
    userName: "SBO Music",
    label: "Moxa Beats",
    upc: "5056828948531",
    issue: "Error",
    date: "22 Jan 2025, 12:45 PM",
    action: "",
    artist: "Arpita Modak",
    page: "QC Approval",
    type: "ERROR",
  },
];
export const support = [
  {
    id: "#236265926502",
    username: "SBM Music",
    title: "Incorrect Metadata Issue",
    date: "22 Jan 2025",
    activity: "2 Months Ago",
    status: "OPEN",
  },
  {
    id: "#236265926502",
    username: "SBM Music",
    title: "Incorrect Metadata Issue",
    date: "22 Jan 2025",
    activity: "2 Months Ago",
    status: "OPEN",
  },
  {
    id: "#236265926502",
    username: "SBM Music",
    title: "Incorrect Metadata Issue",
    date: "22 Jan 2025",
    activity: "2 Months Ago",
    status: "OPEN",
  },
  {
    id: "#236265926502",
    username: "SBM Music",
    title: "Incorrect Metadata Issue",
    date: "22 Jan 2025",
    activity: "2 Months Ago",
    status: "PENDING",
  },
  {
    id: "#236265926502",
    username: "SBM Music",
    title: "Incorrect Metadata Issue",
    date: "22 Jan 2025",
    activity: "2 Months Ago",
    status: "PENDING",
  },
  {
    id: "#236265926502",
    username: "SBM Music",
    title: "Incorrect Metadata Issue",
    date: "22 Jan 2025",
    activity: "2 Months Ago",
    status: "PENDING",
  },
  {
    id: "#236265926502",
    username: "SBM Music",
    title: "Incorrect Metadata Issue",
    date: "22 Jan 2025",
    activity: "2 Months Ago",
    status: "PENDING",
  },
  {
    id: "#236265926502",
    username: "SBM Music",
    title: "Incorrect Metadata Issue",
    date: "22 Jan 2025",
    activity: "2 Months Ago",
    status: "CLOSED",
  },
  {
    id: "#236265926502",
    username: "SBM Music",
    title: "Incorrect Metadata Issue",
    date: "22 Jan 2025",
    activity: "2 Months Ago",
    status: "CLOSED",
  },
  {
    id: "#236265926502",
    username: "SBM Music",
    title: "Incorrect Metadata Issue",
    date: "22 Jan 2025",
    activity: "2 Months Ago",
    status: "CLOSED",
  },
  {
    id: "#236265926502",
    username: "SBM Music",
    title: "Incorrect Metadata Issue",
    date: "22 Jan 2025",
    activity: "2 Months Ago",
    status: "CLOSED",
  },
  {
    id: "#236265926502",
    username: "SBM Music",
    title: "Incorrect Metadata Issue",
    date: "22 Jan 2025",
    activity: "2 Months Ago",
    status: "CLOSED",
  },
  {
    id: "#236265926502",
    username: "SBM Music",
    title: "Incorrect Metadata Issue",
    date: "22 Jan 2025",
    activity: "2 Months Ago",
    status: "CLOSED",
  },
];
export const artistsItems = [
  { name: "Arpita Modak", img: "artist1.png" },
  { name: "Arpita Modak", img: "artist2.png" },
  { name: "Arpita Modak", img: "artist3.png" },
  { name: "Subhamay Karjee", img: "artist4.png" },
  { name: "Arpita Modak", img: "artist5.png" },
  { name: "Arpita Modak", img: "artist4.png" },
  { name: "Arpita Modak", img: "artist5.png" },
  { name: "Arpita Modak", img: "artist6.png" },
  { name: "Arpita Modak", img: "artist4.png" },
  { name: "Arpita Modak", img: "artist8.png" },
];
export const Release_Claim = [
  {
    release: "Buker Bhitor DJ Baje  ",
    img: "release.png",
    release_sample: "0000000000 ",
    type: "YouTube",
    username: "Arpita Modek",
    url: "https://www.youtube.com/",
    date: "12 Jan 2025, 12:24 PM",
    status: "SOLVED",
    reason: "info_icon",
  },
  {
    release: "Buker Bhitor DJ Baje  ",
    release_sample: "0000000000 ",
    type: "YouTube",
    username: "Arpita Modek",
    url: "https://www.youtube.com/",
    date: "12 Jan 2025, 12:24 PM",
    status: "REJECTED",
    reason: "info_icon",
    img: "release.png",
  },
  {
    release: "Buker Bhitor DJ Baje  ",
    img: "release.png",
    release_sample: "0000000000 ",
    type: "YouTube",
    url: "https://www.youtube.com/",
    date: "12 Jan 2025, 12:24 PM",
    status: "PENDING",
    reason: "info_icon",
  },
  {
    release: "Buker Bhitor DJ Baje  ",
    release_sample: "0000000000 ",
    type: "YouTube",
    username: "Arpita Modek",
    url: "https://www.youtube.com/",
    date: "12 Jan 2025, 12:24 PM",
    status: "PENDING",
    reason: "info_icon",
    img: "release.png",
  },
  {
    release: "Buker Bhitor DJ Baje  ",
    img: "release.png",
    release_sample: "0000000000 ",
    type: "YouTube",
    username: "Arpita Modek",
    url: "https://www.youtube.com/",
    date: "12 Jan 2025, 12:24 PM",
    status: "SOLVED",
    reason: "info_icon",
  },
  {
    release: "Buker Bhitor DJ Baje  ",
    img: "release.png",
    release_sample: "0000000000 ",
    type: "YouTube",
    username: "Arpita Modek",
    url: "https://www.youtube.com/",
    date: "12 Jan 2025, 12:24 PM",
    status: "PENDING",
    reason: "info_icon",
  },
  {
    release: "Buker Bhitor DJ Baje  ",
    release_sample: "0000000000 ",
    type: "YouTube",
    username: "Arpita Modek",
    url: "https://www.youtube.com/",
    date: "12 Jan 2025, 12:24 PM",
    status: "PENDING",
    reason: "info_icon",
    img: "release.png",
  },
  {
    release: "Buker Bhitor DJ Baje  ",
    img: "release.png",
    release_sample: "0000000000 ",
    type: "YouTube",
    username: "Arpita Modek",
    url: "https://www.youtube.com/",
    date: "12 Jan 2025, 12:24 PM",
    status: "SOLVED",
    reason: "info_icon",
  },
];
export const transactions = [
  {
    userName: "SBM Music",
    email: "sbmmusic@gmail.com",
    method: "Bank Account",
    methoda_sample: "**** **** **** **72 ",
    amount: "-€1200",
    status: "Rejected",
    date: "22 Jan 2025",
    action: "view_icon",
  },
  {
    userName: "SBM Music",
    email: "sbmmusic@gmail.com",
    method: "Bank Account",
    methoda_sample: "**** **** **** **72 ",
    amount: "-€1200",
    status: "Pending",
    date: "22 Jan 2025",
    action: "view_icon",
  },
  {
    userName: "SBM Music",
    email: "sbmmusic@gmail.com",
    method: "Bank Account",
    methoda_sample: "**** **** **** **72 ",
    amount: "-€1200",
    status: "Pending",
    date: "22 Jan 2025",
    action: "view_icon",
  },
  {
    userName: "SBM Music",
    email: "sbmmusic@gmail.com",
    method: "Bank Account",
    methoda_sample: "**** **** **** **72 ",
    amount: "-€1200",
    status: "Rejected",
    date: "22 Jan 2025",
    action: "view_icon",
  },
  {
    userName: "SBM Music",
    email: "sbmmusic@gmail.com",
    method: "Bank Account",
    methoda_sample: "**** **** **** **72 ",
    amount: "-€1200",
    status: "Success",
    date: "22 Jan 2025",
    action: "view_icon",
  },
  {
    userName: "SBM Music",
    email: "sbmmusic@gmail.com",
    method: "Bank Account",
    methoda_sample: "**** **** **** **72 ",
    amount: "-€1200",
    status: "Pending",
    date: "22 Jan 2025",
    action: "view_icon",
  },
  {
    userName: "SBM Music",
    email: "sbmmusic@gmail.com",
    method: "Bank Account",
    methoda_sample: "**** **** **** **72 ",
    amount: "-€1200",
    status: "Success",
    date: "22 Jan 2025",
    action: "view_icon",
  },
  {
    userName: "SBM Music",
    email: "sbmmusic@gmail.com",
    method: "Bank Account",
    methoda_sample: "**** **** **** **72 ",
    amount: "-€1200",
    status: "Rejected",
    date: "22 Jan 2025",
    action: "view_icon",
  },
  {
    userName: "SBM Music",
    email: "sbmmusic@gmail.com",
    method: "Bank Account",
    methoda_sample: "**** **** **** **72 ",
    amount: "-€1200",
    status: "Pending",
    date: "22 Jan 2025",
    action: "view_icon",
  },
];
export const transactionsHistory = [
  {
    type: "Withdrawn",
    method: "Bank Account",
    methoda_sample: "**** **** **** **72 ",
    amount: "-€1200",
    status: "Pending",
    date: "22 Jan 2025",
    action: "Download Invoice",
  },
  {
    type: "Received",
    method: "—",
    amount: "+€1200",
    status: "Success",
    date: "22 Jan 2025",
    action: "—",
  },
  {
    type: "Received",
    method: "—",
    amount: "+€1200",
    status: "Rejected",
    date: "22 Jan 2025",
    action: "—",
  },
  {
    type: "Received",
    method: "—",
    amount: "+€1200",
    status: "Success",
    date: "22 Jan 2025",
    action: "—",
  },
  {
    type: "Withdrawn",
    method: "PayPal",
    methoda_sample: "********@gmail.com",
    amount: "-€1200",
    status: "Success",
    date: "22 Jan 2025",
    action: "Download Invoice",
  },
  {
    type: "Withdrawn",
    method: "PayPal",
    methoda_sample: "********@gmail.com",
    amount: "-€1200",
    status: "Success",
    date: "22 Jan 2025",
    action: "Download Invoice",
  },
  {
    type: "Received",
    method: "—",
    amount: "+€1200",
    status: "Rejected",
    date: "22 Jan 2025",
    action: "—",
  },
  {
    type: "Received",
    method: "—",
    amount: "+€1200",
    status: "Rejected",
    date: "22 Jan 2025",
    action: "—",
  },
  {
    type: "Withdrawn",
    method: "bKash",
    methoda_sample: "***** ***72",
    amount: "-€1200",
    status: "Success",
    date: "22 Jan 2025",
    action: "Download Invoice",
  },
  {
    type: "Withdrawn",
    method: "bKash",
    methoda_sample: "***** ***72",
    amount: "-€1200",
    status: "Success",
    date: "22 Jan 2025",
    action: "Download Invoice",
  },
];
export const transactionInfo = [
  { label: "Payment Method:", value: "Bank Account" },
  { label: "Account Type:", value: "Current" },
  { label: "Beneficiary Name:", value: "Subhamay Karjee" },
  { label: "Bank Name:", value: "Union Bank of India" },
  { label: "Account Number:", value: "601202120008206" },
  { label: "IFSC:", value: "UBIN0555487" },
  { label: "Business Entity Type:", value: "Private Limited Company" },
  { label: "GST Registered:", value: "Yes" },
  { label: "GST Number:", value: "3945206yhwet" },
];
export const analyticsTable = [
  {
    id: "#9236592605",
    year: "2024",
    month: "December",
    uploadDateTime: "22 Jan 2025, 12:45 PM",
    action: "",
  },
  {
    id: "#9236592605",
    year: "2024",
    month: "December",
    uploadDateTime: "22 Jan 2025, 12:45 PM",
    action: "",
  },
  {
    id: "#9236592605",
    year: "2024",
    month: "December",
    uploadDateTime: "22 Jan 2025, 12:45 PM",
    action: "",
  },
  {
    id: "#9236592605",
    year: "2024",
    month: "December",
    uploadDateTime: "22 Jan 2025, 12:45 PM",
    action: "",
  },
  {
    id: "#9236592605",
    year: "2024",
    month: "December",
    uploadDateTime: "22 Jan 2025, 12:45 PM",
    action: "",
  },
  {
    id: "#9236592605",
    year: "2024",
    month: "December",
    uploadDateTime: "22 Jan 2025, 12:45 PM",
    action: "",
  },
  {
    id: "#9236592605",
    year: "2024",
    month: "December",
    uploadDateTime: "22 Jan 2025, 12:45 PM",
    action: "",
  },
  {
    id: "#9236592605",
    year: "2024",
    month: "December",
    uploadDateTime: "22 Jan 2025, 12:45 PM",
    action: "",
  },
  {
    id: "#9236592605",
    year: "2024",
    month: "December",
    uploadDateTime: "22 Jan 2025, 12:45 PM",
    action: "",
  },
];
export let genreTable = [
  { id: "1", name: "African" },
  { id: "2", name: "Alternative" },
  { id: "3", name: "Ambient" },
  { id: "4", name: "Americana" },
  { id: "5", name: "Big Band" },
  { id: "6", name: "Blues" },
  { id: "7", name: "Children's Music" },
  { id: "8", name: "Christian/Gospel" },
  { id: "9", name: "Classical Crossover" },
  { id: "10", name: "Comedy" },
];
export let subGenreTable = [
  { id: "1", name: "African" },
  { id: "2", name: "Alternative" },
  { id: "3", name: "Ambient" },
  { id: "4", name: "Americana" },
  { id: "5", name: "Big Band" },
  { id: "6", name: "Blues" },
  { id: "7", name: "Children's Music" },
  { id: "8", name: "Christian/Gospel" },
  { id: "9", name: "Classical Crossover" },
  { id: "10", name: "Comedy" },
];
export let languageTable = [
  { id: "1", name: "English" },
  { id: "2", name: "Hindi" },
  { id: "3", name: "Bengali" },
  { id: "4", name: "German" },
  { id: "5", name: "Finnish Band" },
  { id: "6", name: "Italian" },
  { id: "7", name: "Japanese" },
  { id: "8", name: "Norwegian" },
  { id: "9", name: "Spanish" },
  { id: "10", name: "Portuguese" },
];
export let releaseRejectionsTable = [
  {
    id: "1",
    name: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
  },
  {
    id: "2",
    name: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
  },
];
export let labelRejectionsTable = [
  {
    id: "1",
    name: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
  },
  {
    id: "2",
    name: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
  },
];
export let serviceRejectionsTable = [
  {
    id: "1",
    name: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
  },
  {
    id: "2",
    name: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
  },
];
export let settingsTeamMember = [
  {
    id: "1",
    name: "Subhamay Karjee",
    email: "subhamaykarjeeofficial@gmail.com",
    img: "demo.jpg",
  },
  {
    id: "2",
    name: "Arpita Modak",
    img: "Avatar.png",
    email: "arpitamodak@gmail.com",
  },
];
export let settingsMemberCrateria = [
  {
    name: "User",
  },
  {
    name: "Distribution",
  },
  {
    name: "Artist",
  },
  {
    name: "Labels",
  },
  {
    name: "Analytics",
  },
  {
    name: "Service Request",
  },
  {
    name: "Transactions",
  },
  {
    name: "Support",
  },
];
export const artistSocialItems = [
  {
    name: "Spotify",
    img: "spotify-icon.png",
    url: "",
    placeholder: "eg. 6kXwOyEW4VffTqJut6h7J6",
  },
  {
    name: "Apple Music",
    img: "apple-music.png",
    url: "",
    placeholder: "eg. 123456789",
  },
  {
    name: "Facebook Page",
    img: "facebook.png",
    url: "",
    placeholder: "eg. facebook.com/username",
  },
  {
    name: "Instagram Profile",
    img: "instagram.png",
    url: "",
    placeholder: "eg. username",
  },
  {
    name: "Youtube Channel",
    img: "youtube-icon.png",
    url: "",
    placeholder: "eg. youtube.com/username",
  },
];
export const labelSocialItems = [
  {
    name: "Facebook Page",
    img: "facebook.png",
    url: "",
    placeholder: "eg. facebook.com/username",
  },
  {
    name: "Instagram Profile",
    img: "instagram.png",
    url: "",
    placeholder: "eg. username",
  },
  {
    name: "Youtube Channel",
    img: "youtube-icon.png",
    url: "",
    placeholder: "eg. youtube.com/username",
  },
];
export const releaseAlbumInfo = [
  { title: "Release Tittle:", value: "Ami dur hote tomarei dekhechi" },
  { title: "Primary Artists:", value: "Ayuska Bhowmik, Arpita Modak" },
  { title: "Featuring:", value: "Subhamay Karjee" },
  { title: "Genre:", value: "Indian" },
  { title: "Subgenre:", value: "Bengali Indian" },
  { title: "Label name:", value: "Dream records" },
  { title: "Release date:", value: "23 Jan 2025" },
  { title: "Version/Subtittle:", value: "Bengali, English" },
  { title: "Format:", value: "Single" },
  { title: "℗ line:", value: "00012345678" },
  { title: "© line:", value: "87654321000" },
  { title: "Production Year:", value: "2025" },
  { title: "UPC/EAN:", value: "840405732119" },
  { title: "Producer Catalog Number:", value: "340405732119" },
];
export const albumTrackList = [
  {
    title: "Ami Dur Hote Tomarei Dekhechi",
    artist: "Ayuska Bhowmik",
    duration: "04:23",
    content: ["Lyrics line 1", "Lyrics line 2"],
  },
  {
    title: "Tumi Amar",
    artist: "Arijit Singh",
    duration: "03:45",
    content: ["Verse 1", "Verse 2", "Verse 3"],
  },
];
export const singleReleaseATrackData = [
  {
    DSPs: "Spotify",
    Streams: "16,251",
    AlbumDownloads: "0",
    TrackDownloads: "0",
  },
  {
    DSPs: "SloundCloud",
    Streams: "16,251",
    AlbumDownloads: "0",
    TrackDownloads: "0",
  },
  {
    DSPs: "Amazon Prime",
    Streams: "16,251",
    AlbumDownloads: "0",
    TrackDownloads: "0",
  },
  {
    DSPs: "Amazon Music Unlimited",
    Streams: "16,251",
    AlbumDownloads: "0",
    TrackDownloads: "0",
  },
  {
    DSPs: "Deezer",
    Streams: "16,251",
    AlbumDownloads: "0",
    TrackDownloads: "0",
  },
];
export const singleReleaseARevenueData = [
  {
    Total: "Total",
    Revenue: "$16,251",
  },
];
export const releaseTrackDetails = [
  { title: "Track type:", value: "Cover " },
  { title: "Genre:", value: "Indian" },
  { title: "Tittle:", value: "Tere bin" },
  { title: "Sub-genre", value: "Indian Hindi" },
  { title: "Version/Subtittle:", value: "Hindi" },
  { title: "Parental Advisory:", value: "No" },
  { title: "℗ line:", value: "2025 DreamWave Music Group" },
  { title: "Track Tittle Language:", value: "Hindi" },
  { title: "Production Year:", value: "2025" },
  { title: "Lyrics Language:", value: "Hindi" },
  { title: "Publisher:", value: "Auska Bhowmik" },
  {
    title: "Lyrics:",
    value:
      "Tere Bin Main Yun Kaise JiyaKaise Jiya Tere BinTere Bin Main Yun Kaise JiyaKaise Jiya Tere BinLekar Yaad Teri Raaten Meri KatiLekar Yaad Teri Raaten Meri Kati",
  },
  { title: "ISRC Code:", value: "4395734073935" },
];
export const chartData = [
  { month: "Jan", value: 12 },
  { month: "Feb", value: 25 },
  { month: "Mar", value: 50 },
  { month: "Apr", value: 40 },
  { month: "May", value: 52 },
  { month: "Jun", value: 25 },
  { month: "Jul", value: 15 },
  { month: "Aug", value: 33 },
  { month: "Sep", value: 40 },
  { month: "Oct", value: 25 },
  { month: "Nov", value: 35 },
  { month: "Dec", value: 10 },
];
export const releaseCredits = [
  {
    title: "Primary Artist:",
    value: {
      img1: "artist1.png",
      name1: "Arpita Modak",
      img2: "artist1.png",
      name2: "Arpita Modak",
    },
  },
  {
    title: "Lyricist:",
    value: {
      img1: "artist5.png",
      name1: "Subhamay Karjee",
      img2: "artist1.png",
      name2: "Arpita Modak",
    },
  },
  {
    title: "Featuring:",
    value: {
      img1: "artist5.png",
      name1: "Subhamay Karjee",
      img2: "artist1.png",
      name2: "Arpita Modak",
    },
  },
  {
    title: "Composer:",
    value: {
      img1: "artist1.png",
      name1: "Arpita Modak",
      img2: "artist1.png",
      name2: "Arpita Modak",
    },
  },
  {
    title: "Arranger:",
    value: {
      img1: "artist5.png",
      name1: "Subhamay Karjee",
    },
  },
  {
    title: "Producer:",
    value: {
      img1: "artist1.png",
      name1: "Arpita Modak",
    },
  },
];
export const newUsersTable = [
  {
    Username: "Arpita Modak",
    email: "arpita@gmail.com",
    status: "PENDING",
    date: "22 Jan 2025, 12:45 PM",
    action: "",
    img: "Avatar.png",
  },
  {
    Username: "Arpita Modak",
    email: "arpita@gmail.com",
    status: "PENDING",
    date: "22 Jan 2025, 12:45 PM",
    action: "",
    img: "Avatar.png",
  },
  {
    Username: "Arpita Modak",
    email: "arpita@gmail.com",
    status: "PENDING",
    date: "22 Jan 2025, 12:45 PM",
    action: "",
    img: "Avatar.png",
  },
  {
    Username: "Arpita Modak",
    email: "arpita@gmail.com",
    status: "PENDING",
    date: "22 Jan 2025, 12:45 PM",
    action: "",
    img: "Avatar.png",
  },
  {
    Username: "Arpita Modak",
    email: "arpita@gmail.com",
    status: "PENDING",
    date: "22 Jan 2025, 12:45 PM",
    action: "",
    img: "Avatar.png",
  },
  {
    Username: "Arpita Modak",
    email: "arpita@gmail.com",
    status: "PENDING",
    date: "22 Jan 2025, 12:45 PM",
    action: "",
    img: "Avatar.png",
  },
  {
    Username: "Arpita Modak",
    email: "arpita@gmail.com",
    status: "PENDING",
    date: "22 Jan 2025, 12:45 PM",
    action: "",
    img: "Avatar.png",
  },
  {
    Username: "Arpita Modak",
    email: "arpita@gmail.com",
    status: "PENDING",
    date: "22 Jan 2025, 12:45 PM",
    action: "",
    img: "Avatar.png",
  },
  {
    Username: "Arpita Modak",
    email: "arpita@gmail.com",
    status: "PENDING",
    date: "22 Jan 2025, 12:45 PM",
    action: "",
    img: "Avatar.png",
  },
  {
    Username: "Arpita Modak",
    email: "arpita@gmail.com",
    status: "PENDING",
    date: "22 Jan 2025, 12:45 PM",
    action: "",
    img: "Avatar.png",
  },
];
export const activeUsersTable = [
  {
    Username: "Arpita Modak",
    email: "arpita@gmail.com",
    status: "ACTIVE",
    createDate: "22 Jan 2025, 12:45 PM",
    activation: "22 Jan 2025, 12:45 PM",
    action: "",
    img: "Avatar.png",
  },
  {
    Username: "Arpita Modak",
    email: "arpita@gmail.com",
    status: "ACTIVE",
    createDate: "22 Jan 2025, 12:45 PM",
    activation: "22 Jan 2025, 12:45 PM",
    action: "",
    img: "Avatar.png",
  },
  {
    Username: "Arpita Modak",
    email: "arpita@gmail.com",
    status: "ACTIVE",
    createDate: "22 Jan 2025, 12:45 PM",
    activation: "22 Jan 2025, 12:45 PM",
    action: "",
    img: "Avatar.png",
  },
  {
    Username: "Arpita Modak",
    email: "arpita@gmail.com",
    status: "ACTIVE",
    createDate: "22 Jan 2025, 12:45 PM",
    activation: "22 Jan 2025, 12:45 PM",
    action: "",
    img: "Avatar.png",
  },
  {
    Username: "Arpita Modak",
    email: "arpita@gmail.com",
    status: "ACTIVE",
    createDate: "22 Jan 2025, 12:45 PM",
    activation: "22 Jan 2025, 12:45 PM",
    action: "",
    img: "Avatar.png",
  },
  {
    Username: "Arpita Modak",
    email: "arpita@gmail.com",
    status: "ACTIVE",
    createDate: "22 Jan 2025, 12:45 PM",
    activation: "22 Jan 2025, 12:45 PM",
    action: "",
    img: "Avatar.png",
  },
  {
    Username: "Arpita Modak",
    email: "arpita@gmail.com",
    status: "ACTIVE",
    createDate: "22 Jan 2025, 12:45 PM",
    activation: "22 Jan 2025, 12:45 PM",
    action: "",
    img: "Avatar.png",
  },
  {
    Username: "Arpita Modak",
    email: "arpita@gmail.com",
    status: "ACTIVE",
    createDate: "22 Jan 2025, 12:45 PM",
    activation: "22 Jan 2025, 12:45 PM",
    action: "",
    img: "Avatar.png",
  },
  {
    Username: "Arpita Modak",
    email: "arpita@gmail.com",
    status: "ACTIVE",
    createDate: "22 Jan 2025, 12:45 PM",
    activation: "22 Jan 2025, 12:45 PM",
    action: "",
    img: "Avatar.png",
  },
  {
    Username: "Arpita Modak",
    email: "arpita@gmail.com",
    status: "ACTIVE",
    createDate: "22 Jan 2025, 12:45 PM",
    activation: "22 Jan 2025, 12:45 PM",
    action: "",
    img: "Avatar.png",
  },
];
export const suspendUsersTable = [
  {
    Username: "Arpita Modak",
    email: "arpita@gmail.com",
    status: "SUSPENDED",
    createDate: "22 Jan 2025, 12:45 PM",
    suspendDate: "22 Jan 2025, 12:45 PM",
    action: "",
    img: "Avatar.png",
  },
  {
    Username: "Arpita Modak",
    email: "arpita@gmail.com",
    status: "SUSPENDED",
    createDate: "22 Jan 2025, 12:45 PM",
    suspendDate: "22 Jan 2025, 12:45 PM",
    action: "",
    img: "Avatar.png",
  },
  {
    Username: "Arpita Modak",
    email: "arpita@gmail.com",
    status: "SUSPENDED",
    createDate: "22 Jan 2025, 12:45 PM",
    suspendDate: "22 Jan 2025, 12:45 PM",
    action: "",
    img: "Avatar.png",
  },
  {
    Username: "Arpita Modak",
    email: "arpita@gmail.com",
    status: "SUSPENDED",
    createDate: "22 Jan 2025, 12:45 PM",
    suspendDate: "22 Jan 2025, 12:45 PM",
    action: "",
    img: "Avatar.png",
  },
  {
    Username: "Arpita Modak",
    email: "arpita@gmail.com",
    status: "SUSPENDED",
    createDate: "22 Jan 2025, 12:45 PM",
    suspendDate: "22 Jan 2025, 12:45 PM",
    action: "",
    img: "Avatar.png",
  },
  {
    Username: "Arpita Modak",
    email: "arpita@gmail.com",
    status: "SUSPENDED",
    createDate: "22 Jan 2025, 12:45 PM",
    suspendDate: "22 Jan 2025, 12:45 PM",
    action: "",
    img: "Avatar.png",
  },
  {
    Username: "Arpita Modak",
    email: "arpita@gmail.com",
    status: "SUSPENDED",
    createDate: "22 Jan 2025, 12:45 PM",
    suspendDate: "22 Jan 2025, 12:45 PM",
    action: "",
    img: "Avatar.png",
  },
  {
    Username: "Arpita Modak",
    email: "arpita@gmail.com",
    status: "SUSPENDED",
    createDate: "22 Jan 2025, 12:45 PM",
    suspendDate: "22 Jan 2025, 12:45 PM",
    action: "",
    img: "Avatar.png",
  },
  {
    Username: "Arpita Modak",
    email: "arpita@gmail.com",
    status: "SUSPENDED",
    createDate: "22 Jan 2025, 12:45 PM",
    suspendDate: "22 Jan 2025, 12:45 PM",
    action: "",
    img: "Avatar.png",
  },
  {
    Username: "Arpita Modak",
    email: "arpita@gmail.com",
    status: "SUSPENDED",
    createDate: "22 Jan 2025, 12:45 PM",
    suspendDate: "22 Jan 2025, 12:45 PM",
    action: "",
    img: "Avatar.png",
  },
];
export const LablesItems = [
  {
    name: "T series",
    type: "Reject",
    img: "lables-placeholder.png",
    date: "Sep 21, 2024",
  },
  {
    name: "Zee Music Co.",
    type: "Reject",
    img: "Zee-Music.png",
    date: "Sep 21, 2024",
  },
  {
    name: "Saregama",
    type: "Pending",
    img: "Saregama.png",
    date: "Sep 21, 2024",
  },
  {
    name: "Vevo",
    type: "Approved",
    img: "Vevo.png",
    date: "Sep 21, 2024",
  },
  {
    name: "Saregama",
    type: "Pending",
    img: "lables-placeholder.png",
    date: "Sep 21, 2024",
  },
  {
    name: "Steam Music",
    type: "Approved",
    img: "Steam-Music.png",
    date: "Sep 21, 2024",
  },
  {
    name: "Saregama",
    type: "Pending",
    img: "lables-placeholder.png",
    date: "Sep 21, 2024",
  },
  {
    name: "Steam Music India",
    type: "Reject",
    img: "Steam-Music-India.png",
    date: "Sep 21, 2024",
  },
  {
    name: "T series",
    type: "Reject",
    img: "T-series.png",
    date: "Sep 21, 2024",
  },
  {
    name: "Zee Music Co.",
    type: "Reject",
    img: "lables-placeholder.png",
    date: "Sep 21, 2024",
  },
];
